using Microsoft.TypeSpec.Generator.Customizations;

namespace OpenAI.Assistants;

[CodeGenType("UnknownRunStepDetailsToolCallsCodeObjectCodeInterpreterOutputsObject")]
public partial class UnknownRunStepDetailsToolCallsCodeObjectCodeInterpreterOutputsObject
{
}